'use client';
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";
const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart, setCart}}>
      <html lang="en">
        <body className={inter.className}>

          <Header />
          {children}
          <Footer />
        </body>
        </html>
        </CartContext.Provider >
    </ClerkProvider>
  );
}
